status = [
  "docs",
  "Linux python:3.6-slim",
  "Linux python:3.7-slim",
  "Linux python:3.8-slim",
  "Linux python:3.9-slim",
  "Windows python:3.6-windowsservercore",
  "Windows python:3.7-windowsservercore",
  "Windows python:3.8-windowsservercore",
  "Windows python:3.9-windowsservercore",
  "macOS PYTHON:3.6.12",
  "macOS PYTHON:3.7.9",
  "macOS PYTHON:3.8.6",
  "macOS PYTHON:3.9.0",
  "pep517",
]

delete_merged_branches = true
